path=${APP_PATH}
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
mvn_user_password=${MVN_USER_PASSWORD}
srv_cengo_pass=${SRV_CENGO_PASS}
ARK_service_user=${ARK_SERVICE_USER}
srv_apache_user=${SRV_APACHE_USER}
